### ISSUE TITLE
[Bug] Terminal output buffer

### ISSUE THREAD

**Issue by Naccl** [Lakr233/Rayon#1]
**Describe the bug**
Usually occurs when the number of lines printed is very large.
When there are many files in a directory, I typed `ls -l` and get like this

<img width="1252" alt="2022-02-14 07 44 16" src="https://user-images.githubusercontent.com/44741777/153781203-d43843e3-456d-4b8c-bc03-fb20e9ec6659.png">

**To Reproduce**
```shell
$ mkdir test && cd test
$ for i in {001..999}; do touch ${i}.f; done
$ ls -l
```

It seems to be related to the buffer size?

**Comment by Lakr233** [comment]
Fixed.

**Comment by Lakr233** [comment]
If the thing happens again, reopen it........ qaq

**Comment by Lakr233** [comment]
> I'm a little curious how did you solve these weird problems. Can you give me a link to the code? OvO

The control buffer was cut when read from socket. The solution is simple and **🤯** :p

https://github.com/Lakr233/Rayon/blob/main/External/NSRemoteShell/Sources/NSRemoteShell/GenericHeaders.h
