### ISSUE TITLE
Inaccurate Display of RAM info on Synology NAS

### ISSUE THREAD

**Issue by Brabalawuka** [Lakr233/Rayon#12]
Issue: Incorrect RAM Display
Version: latest on iOS

Description: This is the screen shot of my top command on my NAS terminal, it says 17GB cache + 2GB used = 20GB total
![屏幕截图 2022-03-05 170141](https://user-images.githubusercontent.com/31028570/156876725-d596e824-9994-4697-938f-5035cbc39618.png)
 
This is the screen shot of my NAS built in APP, it says 13% used which is same as the one in the top command

![photo_2022-03-05_17-07-46](https://user-images.githubusercontent.com/31028570/156876817-5dadff4d-874d-4773-abd0-b17c9f0aedd7.jpg)

However, in Rayon app it combines the view of cache + swap == 30GB??  
![IMG_0447](https://user-images.githubusercontent.com/31028570/156876861-0d7dca7d-c24d-4cf2-b91d-4323543e22b2.PNG)

Please help fix this!

**Comment by Lakr233** [comment]
Looks like there is a issue on graphic, the data shown here seems to be fine.
<img width="636" alt="截屏2022-03-05 下午5 24 03" src="https://user-images.githubusercontent.com/25259084/156877190-56627c42-2110-4607-b664-821bc407dd2b.png">

**Comment by Lakr233** [comment]
Fixed

**Comment by Brabalawuka** [comment]
> Looks like there is a issue on graphic, the data shown here seems to be fine.
> 
> 
> 
> <img width="636" alt="截屏2022-03-05 下午5 24 03" src="https://user-images.githubusercontent.com/25259084/156877190-56627c42-2110-4607-b664-821bc407dd2b.png">

But the used is supposed to be 2GB instead of 20GB..

**Comment by Lakr233** [comment]
you can't have 2gb used with 16g of cache. cache is inside used.
