### ISSUE TITLE
About Pricing on App Store

### ISSUE THREAD

**Issue by Lakr233** [Lakr233/Rayon#14]
We are planing to raise the price on App Store after April 1st. (so get it now) The main reason for doing so is the "Apple Fee" with Apple Developer Program, and secondly, I actually paid many for copyright assets such as placeholder image at UI8 and a drawer for avatar. ~~Lastly, I feel it is over my due to be a nice man.~~

Here are some statement regrading to this action:

- The app will still be open sourced for any one, compilable and free. (Copyrighted assets are excluded, but doesn't affect you run it.)
- The macOS release will be update at GitHub release with notarized bundle. (If my signing certification still valid, cancel anytime.)
- The iOS release will have a testflight access for anyone in need. Reply to this thread/issue with your email, we will send you invite link or a promotion code, no reason asked. This release will be identical to App Store release.

Overall, buying our app on App Store will support our development. (but any are not guaranteed) The full statement is subjected to change, with or without notification.

**Comment by isontheline** [comment]
Why not In App Purchase (non consumable) ?

This will allow users to try out the app before buying it.

Keep up the good work!

**Comment by Lakr233** [comment]
> Why not In App Purchase (non consumable) ?
> 
> This will allow users to try out the app before buying it.
> 
> Keep up the good work!

Don’t feel like to put ugly IAP code inside my app. Tons of Apple’s review and fruit-ish server make it fails for many.

**Comment by isontheline** [comment]
Many users won't buy Rayon if they can't review it at all.

On my side IAP works well and I have better reviews than my app was paid.

**Comment by Lakr233** [comment]
> Many users won't buy Rayon if they can't review it at all.

The propose of writing this app is totally not making money, so shape it with what I like is important.

> On my side IAP works well

There is some magic I can't tell tho :P

> Tons of Apple’s review

Apple's review for App Store not review at App Store made by user.

I'll consider it. I still got time to think about~

**Comment by isontheline** [comment]
> Apple's review for App Store not review at App Store made by user.

That's all right 😅

**Comment by kmahyyg** [comment]
> Why not In App Purchase (non consumable) ?
> 
> This will allow users to try out the app before buying it.
> 
> Keep up the good work!

IAP is not a good solution since Apple's API is really a sh*t and there're always some unknown bug of IAP callback...

**Comment by Lakr233** [comment]
Promotion Code

macOS

`
NHNXKMF76XXL
MMTX73NPXN9T
PMM9LRY9X7KX
H497ETH7PFXY
L7XK7X3FMLX7
9JJEH7PTJEEM
TEYNMHEET9HM
3AXRHWA6EEXL
4RP93YXXRYMR
97HANTFXPN94
AJEP3R4EHJ7E
FMLRF6TY4KJT
X4N33XHELH4N
NLA77PHHPMAP
ELYYJ73XEYEK
MLMWPPEA9M43
KJMHE4EATRXE
PL446XEYYM4L
6X6WE4WRYK6W
T4M4LK74WFF7
EA97JAMRYR7H
M9RPEL3HN7H9
AE6A9JRL3ELH
63NXJRY63R67
KLNHTYEKF3L6
JKK9TANKK9F4
P7PWKPLY336W
PT9FFTXE7LYF
6AW4KNKPTP4N
Y7F6ETKF6NHH
43M3YLJNEX7F
MWNJEAEJTJHY
7T9WRXNFKRMN
34F76AAXWWF6
P7PHN9XFEH3J
PJ3TNW3FWFNX
N4A4LMKFEAKK
6P36HYJX46AJ
AATK34EWM3W6
E6WR6XXMJY36
WMEA7LX3JXYP
TERFLEWWLF4R
KN3T43EK4WH4
P9EP3P6YYEMN
T4JFEJWPPJYE
93X4TMKR3NY7
E36TRPLKFFY9
PW3KWYHLP33E
E4NNX93YLEE7
AWX4XYHXAHTN
`

iOS
`
9RNRJEE43MHT
TMMA7JFHRTH3
JFTKK6PJYRKH
WWM6H974FJ3E
RELYA3LHHNRF
43K9YM4PPJ6T
NRWKJ6XENTYP
7HJN4PFNLMPX
TT3R4AMEYE3X
9LW9AAJLH64R
79PTLRT47F4L
3A33JLFX3NXA
RPY439XX4LKT
THFNHXYKT4XM
64F7646PPE4W
FMPW7AT7JEWK
F4LTT7EX9934
WH9MRWL3YHKM
NL9MWRLNY6L4
MX979HTLEWFF
FHPNKEF4Y9MP
RX3AWMM9FPW7
EJFTREXLYK6R
YYKYM39M3TKT
E7LLMN743MRH
WR7NJ9NN3HEK
R3HLTLTTAXEK
39RRXX3PY6WA
A4K333R96943
EM6NEH49METT
7747XAWT6R64
PYFHNFXWP9A9
4MLYTF7RARRX
K4REFY4FK9LW
4YWKX6FHK9TA
ERNHKXHY9RFP
LEATJKP6EK4T
YF4H79XLFJ7E
PMTMJMFA9TFL
RKH676ATYY9Y
9ALET9N6KRJL
W9HRRRA7EA9L
9XNN79JNEMLT
MNEYE6N6KRRL
XKF7K3RNREYL
4LMR7FEEJJWR
PTHJW6NWPNMA
EPK9AXPNPEW3
WHYL9H9MNMEM
374TNKJFFJF9
`

Reply your email if code used all.

**Comment by MissLeely** [comment]
我使用了MNEYE6N6KRRL
还像是这个。也可能是上下的其中一个
谢谢

**Comment by Lakr233** [comment]
> 我使用了MNEYE6N6KRRL
> 还像是这个。也可能是上下的其中一个
> 谢谢

现在还不要钱啊这4月1号开始的 🤯🤯🤯🤯🤯🤯

**Comment by lxq1** [comment]
现在还需要发邮件体验吗？

**Comment by tcqiuyu** [comment]
想请问现在这个还能用吗？

**Comment by Lakr233** [comment]
> 想请问现在这个还能用吗？

这些邀请码有效期一个月 应该还能用吧

**Comment by Lakr233** [comment]
> 现在还需要发邮件体验吗？

不需要啊 我没看懂
