### ISSUE TITLE
[bug] Words cannot be displayed in Vim in some cases

### ISSUE THREAD

**Issue by Naccl** [Lakr233/Rayon#2]
**Describe the bug**

**In maximize window or full screen**, when I move the cursor to the front of a word(perhaps a code segment), then quit vim and re-enter vim, sometimes this word will not be displayed until I modify it.
It doesn't seem to happen in smaller window.

https://user-images.githubusercontent.com/44741777/153784346-e7ea03c0-8082-4dad-83c5-0abe87cb55bd.mov

**Comment by Lakr233** [comment]
Debugging with xterm.js is not easy in both cases you’ve report. I’ll keep up with you if I find any solution.

**Comment by Lakr233** [comment]
Fixed
