### ISSUE TITLE
Rayon use a lot of cpu resources 

### ISSUE THREAD

**Issue by Alex222222222222** [Lakr233/Rayon#21]
When I use Rayon to monitor my server, it use considerable amount of cpu resources. Some time it can reach 100% cpu usage, while I was monitoring a single server.

<img width="941" alt="Screenshot 2022-03-07 at 20 20 54" src="https://user-images.githubusercontent.com/61620490/157033929-600395ed-f5ed-4ea7-a3ca-af620bbb747c.png">

If I was monitoring 2 servers, it can reach almost 200% cpu usage.

<img width="942" alt="Screenshot 2022-03-07 at 20 00 22" src="https://user-images.githubusercontent.com/61620490/157034176-5e1e1afb-74a4-473b-93d5-7e33ed0bda73.png">

Memory Usage:

<img width="598" alt="Screenshot 2022-03-07 at 20 21 34" src="https://user-images.githubusercontent.com/61620490/157034637-259b713e-fabc-47b3-8a16-d3c0effcee1b.png">

System information:

<img width="698" alt="Screenshot 2022-03-07 at 20 26 41" src="https://user-images.githubusercontent.com/61620490/157034437-0d594c69-9249-4d66-868b-0f4007e05ab7.png">

**Comment by Alex222222222222** [comment]
I get the same result.

This time, all window was closed. Only a server monitoring service was left in the background.

<img width="499" alt="Screenshot 2022-03-07 at 21 13 23" src="https://user-images.githubusercontent.com/61620490/157042038-573f329d-2b86-4259-8004-a96e4c489fa4.png">

But Rayon still uses a lot of CPU resources.

<img width="941" alt="Screenshot 2022-03-07 at 21 15 49" src="https://user-images.githubusercontent.com/61620490/157042276-58221040-9cca-417f-b057-a6addbe6c507.png">

If I close the monitoring service and only open the main window, the CPU usage was relatively low.

<img width="1012" alt="Screenshot 2022-03-07 at 21 22 37" src="https://user-images.githubusercontent.com/61620490/157042478-ca98ab47-c742-4146-aa7e-e834de010128.png">

<img width="933" alt="Screenshot 2022-03-07 at 21 21 20" src="https://user-images.githubusercontent.com/61620490/157042672-188850c1-88af-405a-bd4c-4aa771800f3b.png">

**Comment by kmahyyg** [comment]
Same problem here: https://github.com/Lakr233/Rayon/issues/16#issuecomment-1062484234 .

**Comment by Lakr233** [comment]
Fixed
