### ISSUE TITLE
machine 无法运用 identity

### ISSUE THREAD

**Issue by zcyc** [Lakr233/Rayon#22]
编辑 machine 选择一个 identity，保存以后还是没有

**Comment by Lakr233** [comment]
你点了那个 ✅ 吗，点返回是不保存的。

**Comment by zcyc** [comment]
> 你点了那个 ✅ 吗，点返回是不保存的。

我点的✅，不是返回。

**Comment by zcyc** [comment]
iPhone 12
iOS 15.3.1

**Comment by zcyc** [comment]
https://user-images.githubusercontent.com/9925064/157197456-09ee808b-15d1-4373-b611-b22a456a2ebf.MOV

**Comment by Lakr233** [comment]
哦这个其实是选择了的 你看这里

<img width="279" alt="截屏2022-03-08 下午4 37 04" src="https://user-images.githubusercontent.com/25259084/157199060-82915ab4-1200-4b90-9225-3e7ae970d792.png">

**Comment by zcyc** [comment]
> 哦这个其实是选择了的 你看这里
> 
> 
> 
> <img width="279" alt="截屏2022-03-08 下午4 37 04" src="https://user-images.githubusercontent.com/25259084/157199060-82915ab4-1200-4b90-9225-3e7ae970d792.png">
> 
> 
> 
> 
嗯，我看到了，但是选了也不能用。刚下下来能用，现在不能用了。图中标黄的地方是展示什么呢，之前能用的时候这里好像有显示密钥。
![image](https://user-images.githubusercontent.com/9925064/157200741-3f4dd2db-5e27-4078-9055-85ca81bafff4.jpeg)

**Comment by Lakr233** [comment]
可以更新一下 新版会在这里现实远端提供的一些信息

**Comment by zcyc** [comment]
> 可以更新一下 新版会在这里现实远端提供的一些信息

还是不能用，什么服务器都不能用。

**Comment by zcyc** [comment]
代理原因，不好意思。麻烦您了。
