### ISSUE TITLE
Missing the Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [Lakr233/Rayon#23]
The project is currently missing the Issue Templates. If you would like to add them, then I would want to add a PR with some relevant **Issue Templates**. Please let me know what do you think about it.

**Comment by Lakr233** [comment]
I've been using GitLab on my self-host own backend, so I don't feel like putting too much effort setting up workflow on GitHub. I would accept your pull requests regrading to this. Thanks for your interest in contribute.
