### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yudingsxt** [Lakr233/Rayon#29]
这边可以加一个按任意键重新连接吗
![8F856890-B506-4053-A919-553843796509](https://user-images.githubusercontent.com/37176460/157385252-51f38e85-1d67-490c-8f55-a8f1b5a5cc0d.jpeg)

**Comment by Lakr233** [comment]
善

**Comment by Lakr233** [comment]
Done

![RPReplay_Final1646992995 MP4](https://user-images.githubusercontent.com/25259084/157845968-f067325d-4cf5-435d-8f25-d6ad021704cf.gif)
