### ISSUE TITLE
Unable to move past license agreement screen on iOS

### ISSUE THREAD

**Issue by kylefmohr** [Lakr233/Rayon#33]
Hello, I cloned this project and built mRayon in XCode, and after installing it on my iPhone 12 Pro Max running iOS 14.8, I am unable to move past the initial license agreement screen. 
![ZigzagMasculineEeve-size_restricted](https://user-images.githubusercontent.com/6644803/157701790-80042cb7-9aba-410a-9075-bc3f12242125.gif)

**Comment by Lakr233** [comment]
This seems to be something wrong on pollyfill-backport api for iOS 14, if you are a developer, set the user default in Xcode console for now.
