### ISSUE TITLE
ios端连接ipv6服务器闪退

### ISSUE THREAD

**Issue by Jv0id** [Lakr233/Rayon#38]
最新版ios端连接ipv6服务器闪退，ipv4服务器连接正常。用其他ssh工具连接ipv6服务器正常。

**Comment by Lakr233** [comment]
咱能具体一点吗 这个我不太好测试。。。。 🥺

![Simulator Screen Shot - iPad mini (6th generation) - 2022-03-14 at 11 32 48](https://user-images.githubusercontent.com/25259084/158100273-53855c53-67ba-4769-b968-89da281e0611.png)

**Comment by Lakr233** [comment]
比方说崩溃日志 看看能不能来一份

**Comment by Jv0id** [comment]
> 比方说崩溃日志 看看能不能来一份

ios的日志在哪里？我没有找到。

**Comment by Jv0id** [comment]
> 咱能具体一点吗 这个我不太好测试。。。。 🥺
> 
> ![Simulator Screen Shot - iPad mini (6th generation) - 2022-03-14 at 11 32 48](https://user-images.githubusercontent.com/25259084/158100273-53855c53-67ba-4769-b968-89da281e0611.png)

iPhone13P，不是Mac版本的。

**Comment by Lakr233** [comment]
> > 比方说崩溃日志 看看能不能来一份
> 
> ios的日志在哪里？我没有找到。

在系统设置里面
https://zhuanlan.zhihu.com/p/336445798

**Comment by Jv0id** [comment]
> 

没有rayon的日志，是其它关键字吗？

**Comment by Lakr233** [comment]
不是 找不到就尴尬了。。。。

**Comment by Lakr233** [comment]
那也有可能是 SwiftUI 炸了。。。。

**Comment by Jv0id** [comment]
我刚才试了一下，突然好了，没有出现闪退的情况，有可能我中午的时候重启了一下手机。
上午试了五六遍都是闪退。

**Comment by Lakr233** [comment]
啊这。。。。。。。。。。。。

我确实发现了一个不安全的方法 但是没有崩溃日志这个很费解。。。

**Comment by Jv0id** [comment]
剩下的就是需要靠你解决了。可能有些地方还有bug吧，可惜帮不了你，我是javaer，不是特别懂Swift.

**Comment by Lakr233** [comment]
~~Java *都不用~~ 🐶
