### ISSUE TITLE
终端字体及大小是否能够修改

### ISSUE THREAD

**Issue by soxft** [Lakr233/Rayon#39]
终端字体及大小是否能够修改呢, 默认的貌似太大了

**Comment by Lakr233** [comment]
字搞那么小干啥嘛 🥺🥺🥺🥺🥺🥺🥺🤯🤯🤯🤯🤯🤯🤯🤯🤯

下个版本我看下怎么搞

**Comment by soxft** [comment]
> 

但是现在的字体大小, 在macbook上看起来就感觉太大了
比较别扭😂 还是希望可以自定义吧

**Comment by Innei** [comment]
@soxft  可以期待下个版本，[Rayon-Terminal](https://github.com/Innei/rayon-terminal) 已经重构。

**Comment by ShikiSuen** [comment]
预设终端字型要不要用 iosevka slab? 更易读一些，且不会占据很宽的空间。
Courier New 的宽度太变态了。
