### ISSUE TITLE
密钥添加以后不能删除，不能修改

### ISSUE THREAD

**Issue by 39499740** [Lakr233/Rayon#43]
我添加密钥以后把2个密钥设置成了一个名称，想改名的时候发现不能删除不能修改，希望可以修改，至少是删除再添加也行

**Comment by Lakr233** [comment]
啥意思 我没听懂

这边不是用名称作为 id 的

**Comment by 39499740** [comment]
私钥列表，列表中的私钥不能删除和修改，再次使用的的时候就分不出来了……因为我添加私钥的时候名字写的一样的

**Comment by Lakr233** [comment]
为啥不能删除呢？我明明放了两个 button

**Comment by 39499740** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/29425312/158573649-b19dcf56-37ba-48ca-bc12-6d043b68f2ba.png">

**Comment by Lakr233** [comment]
<img width="1012" alt="截屏2022-03-16 18 51 05" src="https://user-images.githubusercontent.com/25259084/158573832-4d5e0e47-eb76-437c-81bd-d684df52a4dd.png">

**Comment by 39499740** [comment]
懂了，谢谢
