### ISSUE TITLE
sftp能不能增加编辑文件功能 

### ISSUE THREAD

**Issue by spirytuslove** [Lakr233/Rayon#45]
大佬添加的sftp功能非常棒 UI也很喜欢  希望后期能添加直接编辑文件功能 现在必须下载下来用其他软件编辑再上传有点美中不足 总之还是非常棒的谢谢大佬😀

**Comment by Lakr233** [comment]
这个功能非常难做。。。。。。。。。坑特别大。。。。。。

**Comment by spirytuslove** [comment]
> 这个功能非常难做。。。。。。。。。坑特别大。。。。。。感谢回复 已经非常不错了
