### ISSUE TITLE
[Bug] Cannot output background and will overlay the content when Terminal displays a dialog box

### ISSUE THREAD

**Issue by KooriMoe** [Lakr233/Rayon#7]
#### Describe the bug
When the dialog box appears, the Terminal won't show the background of the box and the Terminal content will output from the beginning after the dialog box disappears (it should be, but the dialog will also keep in the terminal until the new output covers that).   

For example, this is the image when a dialog box appears from dpkg and the purple background didn't show up.   

![](https://img.sakurark.com/2022/02/pXC2A8.png)   

And here's another example about the content output after the dialog disappears.   

![](https://img.sakurark.com/2022/02/niPINC.png)    

#### To Reproduce
Just create a dialog box by using whiptail.
```
whiptail --title "Test Message Box" --msgbox "Create a message box with whiptail. Choose Ok to continue." 10 60  
```

**Comment by Lakr233** [comment]
with an update on xterm side, I made following test:

<img width="1624" alt="截屏2022-03-06 下午5 15 10" src="https://user-images.githubusercontent.com/25259084/156916777-17d1dbff-984b-47e8-8659-f8262c68bfb5.png">

Is this expected behavior or some bug still exists?

**Comment by KooriMoe** [comment]
Well... it seems that this bug has been fixed.
But another bug appears 😂
![](https://img.sakurark.com/2022/03/r8nJYZ.gif)
After pasting something into bash, the black background appears (it should be), but it won't be clear after entering or deleting something🤔...

**Comment by Lakr233** [comment]
That should be another bug at shell level? I’ll close it for now 🥺

**Comment by KooriMoe** [comment]
But it's working fine in the terminal 🤔...
![](https://img.sakurark.com/2022/03/7RGjQU.gif)

**Comment by Lakr233** [comment]
I’ll keep an eye on this.
